require("user.alpha")
require("user.autocommands")
require("user.autopairs")
-- require("user.bufferline")
require("user.cmp")
-- require("user.cokeline")
require("user.colorscheme")
require("user.comment")
require("user.gitsigns")
require("user.keymaps")
require("user.lualine")
require("user.lsp")
require("user.nvim-tree")
require("user.options")
require("user.persisted")
require("user.plugins")
require("user.git-blame")
require("user.telescope")
require("user.toggleterm")
require("user.treesitter")
require("user.whichkey")
require("user.tabnine")

require("user.neovide")
